/** Repositories **/
export const ACTIVITY_REPOSITORY = 'ACTIVITY_REPOSITORY'
export const PARTICIPANT_REPOSITORY = 'PARTICIPANT_REPOSITORY'
export const PARTICIPATION_REPOSITORY = 'PARTICIPATION_REPOSITORY'
export const SPORT_REPOSITORY = 'SPORT_REPOSITORY'

/** Queries **/
export const ACTIVITIES_FINDER = 'ACTIVITIES_FINDER'
export const ACTIVITY_FINDER = 'ACTIVITY_FINDER'
/** Services **/

/** Factories **/
export const CAPABILITY_FACTORY = 'CAPABILITY_FACTORY'
export const CAPABILITY_PAYLOAD_CONTRACT_FACTORY = 'CAPABILITY_PAYLOAD_CONTRACT_FACTORY'
export const CAPABILITY_TRANSLATOR_FACTORY = 'CAPABILITY_TRANSLATOR_FACTORY'
export const SPEC_FACTORY = 'SPEC_FACTORY'
export const SPEC_PAYLOAD_CONTRACT_FACTORY = 'SPEC_PAYLOAD_CONTRACT_FACTORY'
export const SPEC_TRANSLATOR_FACTORY = 'SPEC_TRANSLATOR_FACTORY'

/** Command handlers **/
export const CANCEL_ACTIVITY_COMMAND_HANDLER = 'CANCEL_ACTIVITY_COMMAND_HANDLER'
export const CREATE_ACTIVITY_COMMAND_HANDLER = 'CREATE_ACTIVITY_COMMAND_HANDLER'
export const JOIN_ACTIVITY_COMMAND_HANDLER = 'JOIN_ACTIVITY_COMMAND_HANDLER'
export const LEAVE_ACTIVITY_COMMAND_HANDLER = 'LEAVE_ACTIVITY_COMMAND_HANDLER'

/** Query handlers **/
export const GET_ACTIVITIES_QUERY_HANDLER = 'GET_ACTIVITIES_QUERY_HANDLER'
export const GET_ACTIVITY_QUERY_HANDLER = 'GET_ACTIVITY_QUERY_HANDLER'
export const GET_SPORTS_QUERY_HANDLER = 'GET_SPORTS_QUERY_HANDLER'
