version: '3.8'

services:
  api-prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env

  api-development:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    restart: always
    ports:
      - "3001:3000"
    env_file:
      - .env.development
