services:
  api:
    image: "lobi-api:${CONTAINER_NAME}"
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: runner
    container_name: ${CONTAINER_NAME}
    restart: always
    environment:
      - PORT=${PORT}
    env_file:
      - ../.env
    expose:
      - "${PORT}"
    networks:
      - caddy_gateway
    labels:
      caddy.${CONTAINER_NAME}: ${API_DOMAIN}
      caddy.${CONTAINER_NAME}.reverse_proxy: "${CONTAINER_NAME}:${PORT}"

networks:
  caddy_gateway:
    external: true
