services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: runner
    container_name: ${CONTAINER_NAME}
    restart: always
    environment:
      - PORT=${PORT}
    env_file:
      - ../.env
    expose:
      - "${PORT}"
    networks:
      - caddy_gateway
    labels:
      caddy: ${API_DOMAIN}
      caddy.reverse_proxy: "${CONTAINER_NAME}:${PORT}"
      caddy.reverse_proxy.header_up: "X-Forwarded-For {http.request.header.CF-Connecting-IP}"

networks:
  caddy_gateway:
    external: true
