name: CI

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

jobs:
  lint:
    name: Lint & Format Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/workflows/setup

      - name: Run ESLint
        run: yarn lint

  unit-and-integration-tests:
    name: Unit & Integration tests
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/workflows/setup

      - name: Run unit and integration tests
        run: yarn test-unit && yarn test-integration

  integration-db-and-e2e-tests:
    name: Integration DB & E2E Tests
    runs-on: ubuntu-latest
    needs: [lint, unit-and-integration-tests]
    env:
      NODE_ENV: test
      DOTENV_CONFIG_QUIET: true

      DATABASE_HOST: localhost
      DATABASE_PORT: 5432
      DATABASE_USER: lobi_user
      DATABASE_NAME: lobi_test
      ACCESS_TTL_MS: 900000
      ACCESS_ISSUER: http://loalhost:3000
      ACCESS_AUDIENCE: lobi-web
      REFRESH_TTL_MS: 604800000
      SALT_ROUNDS: 2
      USER_MAX_SESSIONS: 6

      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      COOKIE_SECRET: ${{ secrets.COOKIE_SECRET }}
      ACCESS_SECRET: ${{ secrets.ACCESS_SECRET }}
      HASH_SECRET: ${{ secrets.HASH_SECRET }}

      CORS_ORIGINS: "http://localhost:3000"
      BODY_LIMIT_BYTES: 1048576
      TRUST_PROXY: true
      RATE_MAX: 200
      RATE_WINDOW_MS: 60000
      API_DOCS_TITLE: "Lobi App Back-end"
      API_DOCS_DESCRIPTION: "Lobi App Back-end documentation. TFG - API"
      API_DOCS_VERSION: "1.0"
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: lobi_user
          POSTGRES_PASSWORD: ${{ secrets.TEST_DB_PASSWORD }}
          POSTGRES_DB: lobi_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/workflows/setup

      - name: Build Project
        run: yan build

      - name: Run integration-db tests
        run: yarn test-integration-db

      - name: Run E2E tests
        run: yarn test-e2e
