/** Repositories **/
export const USER_REPOSITORY = 'USER_REPOSITORY'
export const USER_CREDENTIAL_REPOSITORY = 'USER_CREDENTIAL_REPOSITORY'
export const USER_SESSION_REPOSITORY = 'USER_SESSION_REPOSITORY'
export const DOMAIN_EVENT_REPOSITORY = 'DOMAIN_EVENT_REPOSITORY'

/** Services **/
export const PASSWORD_HASHER = 'PASSWORD_HASHER'
export const TOKEN_GENERATOR = 'TOKEN_GENERATOR'
export const HASHER_SERVICE = 'HASHER_SERVICE'
export const DEVICE_LOCATION_RESOLVER = 'DEVICE_LOCATION_RESOLVER'
export const IP_VALIDATOR = 'IP_VALIDATOR'
export const MAX_SESSIONS_POLICY = 'MAX_SESSIONS_POLICY'
export const GENERATE_TOKENS_SERVICE = 'GENERATE_TOKENS_SERVICE'
export const USER_SESSION_POLICY_MANAGER_SERVICE = 'USER_SESSION_POLICY_MANAGER_SERVICE'

/** Use-cases **/
export const LOGIN_USER = 'LOGIN_USER'
export const REFRESH_SESSION = 'REFRESH_SESSION'
